# Generated by Django 5.2.8 on 2025-12-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QtestApp', '0002_alter_choice_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='chapter',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
