# Generated by Django 5.2.8 on 2025-12-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QtestApp', '0003_test_chapter_test_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('chapter', 'Chapter Tests'), ('life_in_uk', 'Life in the UK Tests'), ('practice', 'Practice Tests')], default='chapter', max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='series_number',
            field=models.IntegerField(default=0, help_text='Test number in the series'),
        ),
    ]
