# Generated by Django 5.2.8 on 2025-12-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QtestApp', '0004_test_category_test_is_featured_test_series_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='correct_answers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsession',
            name='time_taken',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='total_questions',
            field=models.IntegerField(blank=True, default=24, null=True),
        ),
    ]
