# Generated by Django 5.2.1 on 2025-12-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QtestApp', '0005_testsession_correct_answers_testsession_passed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('has_toilet', models.BooleanField(default=False)),
                ('has_wheelchair', models.BooleanField(default=False)),
                ('has_dog', models.BooleanField(default=False)),
            ],
        ),
    ]
