# Generated by Django 5.2.1 on 2025-12-21 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QtestApp', '0008_exam_alter_location_has_dog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='QtestApp.exam'),
        ),
    ]
